services:
    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        volumes:
            - ./mongo_data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${ACCOUNT}
            MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${ACCOUNT}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${PASSWORD}
            ME_CONFIG_MONGODB_URL: ${MONGODB_URI}
            ME_CONFIG_BASICAUTH: false

    backend:
        build: ./backend
        depends_on: ["mongo"]
        environment:
            ENV: ${ENV}
            MONGODB_URI: ${MONGODB_URI}
        ports: ["8080:8080"]
