/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { EntriesResponse } from '../models';
// @ts-ignore
import type { EntryInput } from '../models';
// @ts-ignore
import type { EntryResponse } from '../models';
// @ts-ignore
import type { HTTPValidationError } from '../models';
/**
 * EntriesApi - axios parameter creator
 * @export
 */
export const EntriesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Add Entry
         * @param {EntryInput} entryInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addEntry: async (entryInput: EntryInput, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'entryInput' is not null or undefined
            assertParamExists('addEntry', 'entryInput', entryInput)
            const localVarPath = `/entries`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(entryInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete Entry
         * @param {string} id 削除するエントリーのID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteEntry: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteEntry', 'id', id)
            const localVarPath = `/entries`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Entries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEntries: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/entries`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update Entry
         * @param {string} id エントリーID
         * @param {EntryInput} entryInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateEntry: async (id: string, entryInput: EntryInput, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateEntry', 'id', id)
            // verify required parameter 'entryInput' is not null or undefined
            assertParamExists('updateEntry', 'entryInput', entryInput)
            const localVarPath = `/entries`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(entryInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EntriesApi - functional programming interface
 * @export
 */
export const EntriesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EntriesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Add Entry
         * @param {EntryInput} entryInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addEntry(entryInput: EntryInput, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EntryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addEntry(entryInput, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EntriesApi.addEntry']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete Entry
         * @param {string} id 削除するエントリーのID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteEntry(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EntriesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteEntry(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EntriesApi.deleteEntry']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Entries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEntries(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EntriesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getEntries(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EntriesApi.getEntries']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update Entry
         * @param {string} id エントリーID
         * @param {EntryInput} entryInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateEntry(id: string, entryInput: EntryInput, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EntryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateEntry(id, entryInput, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EntriesApi.updateEntry']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EntriesApi - factory interface
 * @export
 */
export const EntriesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EntriesApiFp(configuration)
    return {
        /**
         * 
         * @summary Add Entry
         * @param {EntryInput} entryInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addEntry(entryInput: EntryInput, options?: RawAxiosRequestConfig): AxiosPromise<EntryResponse> {
            return localVarFp.addEntry(entryInput, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete Entry
         * @param {string} id 削除するエントリーのID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteEntry(id: string, options?: RawAxiosRequestConfig): AxiosPromise<EntriesResponse> {
            return localVarFp.deleteEntry(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Entries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEntries(options?: RawAxiosRequestConfig): AxiosPromise<EntriesResponse> {
            return localVarFp.getEntries(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update Entry
         * @param {string} id エントリーID
         * @param {EntryInput} entryInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateEntry(id: string, entryInput: EntryInput, options?: RawAxiosRequestConfig): AxiosPromise<EntryResponse> {
            return localVarFp.updateEntry(id, entryInput, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EntriesApi - interface
 * @export
 * @interface EntriesApi
 */
export interface EntriesApiInterface {
    /**
     * 
     * @summary Add Entry
     * @param {EntryInput} entryInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EntriesApiInterface
     */
    addEntry(entryInput: EntryInput, options?: RawAxiosRequestConfig): AxiosPromise<EntryResponse>;

    /**
     * 
     * @summary Delete Entry
     * @param {string} id 削除するエントリーのID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EntriesApiInterface
     */
    deleteEntry(id: string, options?: RawAxiosRequestConfig): AxiosPromise<EntriesResponse>;

    /**
     * 
     * @summary Get Entries
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EntriesApiInterface
     */
    getEntries(options?: RawAxiosRequestConfig): AxiosPromise<EntriesResponse>;

    /**
     * 
     * @summary Update Entry
     * @param {string} id エントリーID
     * @param {EntryInput} entryInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EntriesApiInterface
     */
    updateEntry(id: string, entryInput: EntryInput, options?: RawAxiosRequestConfig): AxiosPromise<EntryResponse>;

}

/**
 * EntriesApi - object-oriented interface
 * @export
 * @class EntriesApi
 * @extends {BaseAPI}
 */
export class EntriesApi extends BaseAPI implements EntriesApiInterface {
    /**
     * 
     * @summary Add Entry
     * @param {EntryInput} entryInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EntriesApi
     */
    public addEntry(entryInput: EntryInput, options?: RawAxiosRequestConfig) {
        return EntriesApiFp(this.configuration).addEntry(entryInput, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete Entry
     * @param {string} id 削除するエントリーのID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EntriesApi
     */
    public deleteEntry(id: string, options?: RawAxiosRequestConfig) {
        return EntriesApiFp(this.configuration).deleteEntry(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Entries
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EntriesApi
     */
    public getEntries(options?: RawAxiosRequestConfig) {
        return EntriesApiFp(this.configuration).getEntries(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update Entry
     * @param {string} id エントリーID
     * @param {EntryInput} entryInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EntriesApi
     */
    public updateEntry(id: string, entryInput: EntryInput, options?: RawAxiosRequestConfig) {
        return EntriesApiFp(this.configuration).updateEntry(id, entryInput, options).then((request) => request(this.axios, this.basePath));
    }
}

