/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Id } from './id';
// May contain unused imports in some cases
// @ts-ignore
import type { Memo } from './memo';

/**
 * 
 * @export
 * @interface EntryOutput
 */
export interface EntryOutput {
    [key: string]: any;

    /**
     * 
     * @type {Id}
     * @memberof EntryOutput
     */
    'id'?: Id;
    /**
     * 記録日（必須、YYYY-MM-DD形式）
     * @type {string}
     * @memberof EntryOutput
     */
    'record_date': string;
    /**
     * メンタルスコア（必須、0〜5の整数）
     * @type {number}
     * @memberof EntryOutput
     */
    'mood_score': number;
    /**
     * 睡眠時間（必須、0以上の小数）
     * @type {number}
     * @memberof EntryOutput
     */
    'sleep_hours': number;
    /**
     * 
     * @type {Memo}
     * @memberof EntryOutput
     */
    'memo'?: Memo;
}

